glslangValidator Block.vert
glslangValidator Block.frag
glslangValidator Deferred.vert
glslangValidator Deferred.frag
glslangValidator Deferred2.vert
glslangValidator Deferred2.frag
glslangValidator HandItem.vert
glslangValidator HandItem.frag
glslangValidator Line.vert
glslangValidator Line.frag
glslangValidator PiP.vert
glslangValidator PiP.frag
glslangValidator Shadow.vert
glslangValidator Shadow.frag
glslangValidator Skybox.vert
glslangValidator Skybox.frag
glslangValidator Sun.vert
glslangValidator Sun.frag
glslangValidator Test.vert
glslangValidator Test.frag
pause